apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hexagonal-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-hexagonal-template
  template:
    metadata:
      labels:
        app: java-hexagonal-template
    spec:
      containers:
        - name: app
          image: java-hexagonal-template:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_DATABASE
              value: payment_management
